export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGOIRES_START: "category/FETCH_CATEGORIES_START",
  FETCH_CATEGOIRES_SUCCESS: "category/FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGOIRES_FAILED: "category/FETCH_CATEGORIES_FAILED",
}